name: Build and Run Tests and Lint Files
"on": push
jobs:
  unit_test-lint:
    name: continue integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
          npm run build
          npm run test:unit
          npm run lint
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: http://localhost:3000
      - name: Copy test execution videos
        run: |
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
          mkdir public
          mkdir -p /cypress/snapshots 
          cp -r /cypress/videos /public/videos
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-snapshots
          path: cypress/snapshots
      - name: Merge test results into one
        run: npm run report:merge
      - name: Generate HTML report
        run: npm run report:generate
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@WIBR45919.noreply.github.com'
