name: Build and Run Tests and Lint Files
"on": push
jobs:
  unit_test-lint:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          npm ci
          npm run build
          npm run test:unit
          npm run lint
